"""
Pydantic models for Codex-style dataset enrichment.

This module defines the data structures for:
- DatasetLoadedEvent: Emitted when a dataset is loaded, triggers enrichment
- DatasetEnrichmentMetadata: Rich metadata generated by the enrichment LLM
- ColumnSemantics: Semantic information about individual columns
"""

from datetime import datetime, timezone
from typing import Any, Dict, List

from pydantic import BaseModel, Field


def _utc_now() -> datetime:
    """Return current UTC time as a timezone-aware datetime."""
    return datetime.now(timezone.utc)


class ColumnSemantics(BaseModel):
    """Semantic information about a column."""

    name: str
    """The column name."""

    description: str
    """Human-readable description of what this column represents."""

    semantic_type: str
    """
    The semantic type of the column. Common values:
    - identifier: Primary key or unique identifier
    - dimension: Categorical/grouping column
    - measure: Numeric value for aggregation
    - timestamp: Date/time column
    - category: Low-cardinality categorical
    - text: Free-form text
    """

    uniqueness: str = "unknown"
    """
    Uniqueness characteristic. Values:
    - unique: All values are unique (potential PK)
    - mostly_unique: High cardinality, few duplicates
    - low_cardinality: Few distinct values (good for grouping)
    - unknown: Not yet analyzed
    """

    is_primary_key_candidate: bool = False
    """Whether this column could serve as a primary key."""


class DatasetEnrichmentMetadata(BaseModel):
    """
    Rich metadata for a dataset (Codex-style enrichment).

    This metadata is generated by analyzing the dataset structure,
    content, and patterns to provide context for data analysis.
    """

    dataset_name: str
    """Name of the dataset this enrichment describes."""

    enrichment_timestamp: datetime = Field(default_factory=_utc_now)
    """When this enrichment was generated."""

    table_purpose: str
    """Brief description of what this table is for."""

    table_description: str
    """Detailed description of the table's contents and structure."""

    grain_description: str
    """What each row in this table represents (the granularity)."""

    primary_key_candidates: List[str] = Field(default_factory=list)
    """Column names that could serve as primary keys."""

    columns: List[ColumnSemantics] = Field(default_factory=list)
    """Semantic information for each column."""

    row_count: int
    """Number of rows in the dataset."""

    column_count: int
    """Number of columns in the dataset."""

    freshness_indicators: Dict[str, Any] = Field(default_factory=dict)
    """
    Information about data freshness. Keys might include:
    - date_range: "2023-01-01 to 2024-12-31" or {"start_date": "...", "end_date": "..."}
    - latest_record: "2024-12-15"
    """

    recommended_usage: List[str] = Field(default_factory=list)
    """Suggested analyses or queries for this dataset."""

    when_to_use: str = ""
    """Guidance on when to use this dataset vs alternatives."""

    limitations: List[str] = Field(default_factory=list)
    """Known limitations, caveats, or data quality issues."""


class DatasetLoadedEvent(BaseModel):
    """
    Event emitted when a dataset is loaded, triggers enrichment.

    This event is emitted by the DatasetLoadedEmitter tool wrapper
    after a successful load_file operation. It is routed to the
    enrichment LLMAgent for metadata generation.
    """

    dataset_name: str
    """Name assigned to the loaded dataset."""

    row_count: int
    """Number of rows in the dataset."""

    column_count: int
    """Number of columns in the dataset."""

    columns: List[str]
    """List of column names."""

    column_schema: Dict[str, str]
    """Column name to dtype mapping (e.g., {"id": "int64", "name": "object"})."""

    sample_data: List[Dict]
    """First few rows as dictionaries for LLM analysis."""

    load_summary: str
    """Original output from the load_file tool."""
