from typing import Any, Dict, List, Optional

from pydantic import BaseModel, Field


class ReActStep(BaseModel):
    """Single step in the ReAct reasoning trace."""

    thought: Optional[str] = None
    """The reasoning/thought from the LLM before taking action."""

    action: str
    """The name of the tool that was called."""

    action_input: Dict[str, Any]
    """The input arguments passed to the tool."""

    observation: str
    """The result returned from the tool execution."""


class ReActRequest(BaseModel):
    """Request message for the ReActAgent."""

    query: str
    """The user query to process using the ReAct pattern."""

    context: Optional[Dict[str, Any]] = None
    """Optional additional context to include in the request."""


class ReActResponse(BaseModel):
    """Response message from the ReActAgent."""

    answer: str
    """The final answer generated by the agent."""

    trace: List[ReActStep] = Field(default_factory=list)
    """The reasoning trace showing all steps taken to arrive at the answer."""

    iterations: int = 0
    """The number of iterations taken to complete the task."""

    success: bool = True
    """Whether the agent successfully completed the task."""

    error: Optional[str] = None
    """Error message if the agent failed to complete the task."""
